### ISSUE TITLE
Show Rss Feed

### ISSUE THREAD

**Issue by TheKapitan** [mipstian/catch#101]
Once i migrated to the New Show RSS page and generate a new rss feed, it no longer works in Catch.  The feed works fine in uTorrent.

**Comment by miguelmichan** [comment]
Same problem here.

**Comment by mipstian** [comment]
Make sure you're running Catch 1.9.3, and if that still doesn't work, please reply here!

**Comment by TheKapitan** [comment]
Thanks, 
I had thought i was running the latest version but i guess not. 

MATT
