### ISSUE TITLE
Updates Failing

### ISSUE THREAD

**Issue by SGans1** [mipstian/catch#102]
I just wrote an email to the developer, not realizing I should probably post here. My Episode updates are failing. I noticed today that the last successful download was early morning on January 30th (today's February 2nd). I'd had the checking time limit set, but have unset it and still am getting fails. My console error says:
2/2/16 4:49:31.331 PM Catch[368]: Scheduler tick
2/2/16 4:49:31.331 PM Catch[368]: Scheduler status updated (polling = 1, checking = 1)
2/2/16 4:49:31.333 PM com.giorgiocalderolla.Catch.CatchFeedHelper[4750]: Checking feed
2/2/16 4:49:31.334 PM com.giorgiocalderolla.Catch.CatchFeedHelper[4750]: Downloading feed http://showrss.info/rss.php?user_id=286266&hd=null&proper=null&namespaces=true
2/2/16 4:49:31.699 PM com.giorgiocalderolla.Catch.CatchFeedHelper[4750]: Feed downloaded
2/2/16 4:49:31.699 PM com.giorgiocalderolla.Catch.CatchFeedHelper[4750]: Parsing feed
2/2/16 4:49:31.700 PM Catch[368]: Scheduler status updated (polling = 1, checking = 0)

SOME time around there, I'd installed the MacOS security update. Could that have made a change? Is there a port I need to open, that I'm not finding? Any help will be appreciated.

Thanks!

I'm on a MacPro 5,1. MacOS 10.9.5

**Comment by mipstian** [comment]
I've noticed something similar on my box, but it seemed like a UI glitch to me. If the update was in fact failing, there should be something in Console that indicates why. Are your updates actually failing (i.e. are new torrents not downloaded)?

**Comment by SGans1** [comment]
Hi. Yeah - they are failing. Worse than I expected, actually. That January 30th download was of a January 24th episode.

I've written in to GitHub too, as I saw some threads there, but heard nothing.

I WISH it was a UI glitch! Up to this, it was working perfectly! Love this app.... and am shocked there're no errors in Console - but I can't figure out what's up. Maybe there's a port I need to open in my security prefs or something, but it hasn't touched the System Preference it seems, I don't even get a chance to "allow" it...

If you have any ideas, I'd love to hear them - or should I be trying to get help on Github and not buy you?

Thanks!
Stephanie

**Comment by mipstian** [comment]
This is GitHub :)

Don't worry, we'll sort it out. First off, make sure you're running the latest version (1.9.3).

Second, if that doesn't fix it, can you post your feed url here so I can take a look at its contents?

**Comment by SGans1** [comment]
HA! I didn't realize this was actually ON GitHub!!! :)

I am definitely running 1.9.3 of the app. In fact, that was one of my tests: Quit, uninstall, reinstall from a fresh download...

But - my feed url is:
http://showrss.info/user/23300.rss?magnets=true&namespaces=true&name=null&quality=null&re=null

Of course, this is off the new ShowRSS feed - as it will no longer let me log in to the old one... but I did do the migration after the problem began (only a few days ago), because I didn't realize at the time that the downloads weren't working!

THANK YOU!!!

**Comment by mipstian** [comment]
Ok, so I checked your feed and it looks ok. It contains new torrents even from today, so something's off.

I've tried setting Catch to your feed on my Mac and it grabbed everything just fine tho.

Do you see the latest episodes in "Recent Episodes..."? I'm starting to think Catch did its job but something went wrong with the torrent client, or communicating with it.

**Comment by SGans1** [comment]
Hmmm... so what I'd meant by the previous not knowing I was on Github was that I was responding to emails! Didn't realize it went right on here! HAH!

I know it's not the torrent client, because I don't have them automatically download. I mean... I don't download the file right away. I collect the torrent files and only download the files I want to watch... So it seems that Catch isn't pulling any files from that RSS feed, somehow. Not sure I'm making sense here.

Y'know... I just noticed - I'd copied the feed url from the LaunchRSS2 page -and looked in my own preferences - I see that the link's actually DIFFERENT! But... the problem happened before my upgrade... I'm going to try the link I posted above, and I'll be back in touch... Thanks...

**Comment by mipstian** [comment]
Well that's your problem right there. You have magnet links enabled in your feed, so no .torrent files are ever downloaded. Try turning them off. You can easily just replace "magnets=true" with "magnets=false" in your feed URL.

**Comment by SGans1** [comment]
Actually - weirdly - the url I'd HAD in the preferences was WAY different, but it worked (both "in" the app, and in actual resulting .torrent files) for a long time... it was:
http://showrss.info/rss.php?user_id=286266&hd=null&proper=null&namespaces=true

Now, I've changed to the actual link to the one I specified above, and the APP thinks things downloaded, but you're right - now .torrent files didn't arrive... UGH! Gonna change the true to false now, and see what happens. Hopefully, it'll go back and download the .torrents it thinks it'd downloaded...

I'll update as soon as I know more. Thanks!

**Comment by mipstian** [comment]
Hey sorry I missed your update. Glad it worked out.

Magnet links are just an alternative way of getting torrents into your torrent client, without downloading a .torrent file. They are a more streamlined solution, but (at least with Catch) they do require that a torrent client (who registers for magnet links) is installed on the same machine at the time when the feed is checked. That's not an issue for me, and I like not having to deal with leftover .torrent files in the Trash :)

**Comment by SGans1** [comment]
Thanks for the explanation! Now, I get it. I do have torrent clients that I know give me a magnet option - but I work often with screen sharing. I'm glad it's not opening a torrent client in the middle of my work! Thank you - VERY much for your help!

**Comment by mipstian** [comment]
Sure thing!

**Comment by mipstian** [comment]
The original report of "updates failing" was a UI fluke and fixed by 106863b5fdf1e78d1bd28a041e31cfa31d87539a
