### ISSUE TITLE
new ShowRSS site link update

### ISSUE THREAD

**Issue by skepticus** [mipstian/catch#104]
The "Launch ShowRSS" menu feature takes us to the old site- any quick way to fix this?

**Comment by mipstian** [comment]
Click the giant "Go to new ShowRSS" button when you get there :) This issue will solve itself when new showrss supplants the old version. Duplicate of #84

**Comment by skepticus** [comment]
> On 02 03, 2016, at 19:37, Giorgio Calderolla <notifications@github.com> wrote:
> 
> Click the giant "Go to new ShowRSS" button when you get there :) This issue will solve itself when new showrss supplants the old version.

Ah, I do click that. Was wanting to reduce that step.

And, sorry, didn’t know I was duplicating something.

Waiting is.

- Wade
