### ISSUE TITLE
Where the ...

### ISSUE THREAD

**Issue by qnitech** [mipstian/catch#106]
Hello guys,
I use the 1.9.3 version of catch in France ... on a french computer (maybe that is the reason ...<;o))
Since this version, it says as usually that he had downloaded some files ... but I can't see them in the directory they supposed to be ... 
After the update, I've tried a proper removal and à proper install, changing the target directory.
One other thing I did is signup for the new ShowRss account ... but I doubt that is causing the issue ...
Thanks for your help.
John

**Comment by mipstian** [comment]
Are you by chance using magnet links? If you want to have .torrent files, you should turn that off.

**Comment by qnitech** [comment]
aha ... I've tried lot of thing but not that ... (dumbass me !!) it is logic ... why the ... did'nt have I think about the only tuning that can be the cause of my torment ... 
Thanks mipstian !!
