### ISSUE TITLE
new showrss feed link not accepted

### ISSUE THREAD

**Issue by ericb321** [mipstian/catch#107]
I migrated to the new showrss, and after a few days I realized no new shows were being downloaded. Then I noticed that the new showrss has a different feed link. Pasted that in to the Catch preferences, but when I try to click "OK" to submit the change, the dialog box shakes, and a yellow exclamation mark icon appears next to the new feed link. Showrss is dead in the water for me.

**Comment by mipstian** [comment]
Just update to the latest version of Catch. New ShowRSS is only supported in 1.9.3+
