### ISSUE TITLE
"open automatically" cannot be disabled

### ISSUE THREAD

**Issue by effervescentia** [mipstian/catch#110]
I had catch configured to automatically download torrent files into a dropbox folder which would be synched and picked up by my remote torrent server. As of the update to support the new showRSS I've found that the checkbox for "open automatically" doesn't actually toggle that functionality and so my torrent files are never downloaded and I'm left fighting with my local torrent client which is also set up to download automatically.

**Comment by mipstian** [comment]
Sounds like you're accidentally using magnets! Try disabling them and see if you get the behavior you're looking for.

**Comment by effervescentia** [comment]
Yup :P that's done it. Thank you kindly
