### ISSUE TITLE
Invalid torrent files are downloaded

### ISSUE THREAD

**Issue by niltz** [mipstian/catch#112]
Many times the torrent file that is downloaded is invalid. When I inspect the file, the contents are:

```
<h1>Torrent not found</h1><p>Torrent not found in any of the providers. Retrying later.<br /><small>Cached miss.</small></p>
```

In these cases, the file is also saved with a `.torrent.html.torrent` extension instead of just `.torrent`

**Comment by mipstian** [comment]
Super sure you're running the latest version? https://github.com/mipstian/catch/releases/latest

**Comment by mipstian** [comment]
Closing due do inactivity. Please reply here if the issue isn't resolved.

**Comment by niltz** [comment]
Sorry. Just got around to checking the version. I had an older version (1.9.1) so I just updated it. I thought catch updated itself automatically though.

**Comment by mipstian** [comment]
Yup, that's under investigation, see #103
