### ISSUE TITLE
Magnets downloading all sorts of stuff I don't want

### ISSUE THREAD

**Issue by SGans1** [mipstian/catch#113]
Hi.
At least, I THINK it's the magnets! We'd had a problem a couple of weeks ago, when you clarified what the magnets meant, and why I wasn't finding my torrent files downloading. At that time, I turned off magnets and all was well. But, I hadn't realized - the magnets had downloaded about 200 programs I'd never subscribed to, and movies also! Like, they were completely random! Today, I deleted those items from my system, and thought it was done, until I saw that at least episodes of random programs downloaded again. Somehow, magnets got RE-checked, so I've checked it off again.

Thing is - those magnets could be cool! But, my torrent files are downloading fine, and in the right place, and these magnet files are so very random, there's no controlling them. In fact, my Catch menu says my last download was 5:54pm today, and I just found magnet files downloaded at 8pm. 

I'm hoping magnets STAYS unchecked for now, but if ever I wanted to use them, shouldn't they be downloading stuff I want? Oh - and the RSS feeds... I have no movies on my list, yet it downloaded dozens of movies to my movie folder. One more thing- none of these folders are the usual "home" folder folders, I use a different drive with a whole setup of directories, and it magically knows to put the movies in THAT folder. Wild!

Edit: So, I did turn off Magnets on the new RSS page, only to find just now that they were re-enabled. My choice to keep them off won't stick. Got 6 more movies tonight. The hard drive's big, but not SO big that I can store all these files...

**Comment by mipstian** [comment]
Ok there's some confusion here, let me try to take it point by point:
1) It's normal that the magnets option on ShowRSS turns back on. That only configures the feed address you see at the bottom of that page. Once you copy that, you're fine. If your feed address says "magnets=false" in it, magnets are off. Please check and let me know.
2) Catch will only download what's in your ShowRSS feed. And there aren't programs or movies there, so I highly doubt Catch is downloading them (or initiating their download).
3) Catch's menu says "Last Update" which means the last time the feed was checked. Everything it downloads is in the "Recent Episodes" window. There you will find the times at which your feed's items were downloaded. I bet there's only tv shows there. Please check and let me know.

My guess is you're either infected with some weird malware or have subscribed to some other download feed that has nothing to do with Catch or ShowRSS.

**Comment by SGans1** [comment]
1) So, that’s weird. I DO remember you having me change the setting to false last month - and I did. Now, it shows TRUE! (per your response #1). I’m going to change it BACK to FALSE, and hope that sticks. I have NO idea how it got changed back to true…

OH! That’s it! I change “Link Type” in the top to “Use Mirror URLs” (which is the only other option up there), and it goes to false. PIn our previous conversation, we were still on the old RSS feed, in which I could change that manually. There’s no way to manually change the custom feed address that I can see. But it’s THAT setting that seems to constantly reset itself. The Link Type goes back to “Use Magnets in Feed” as soon as I get off the page, and that changes the custom feed to true…

2) I can’t imagine what else may be downloading movies then… and low rez at that… Perhaps there’s a channel I have in Plex (Activity monitor does show high activity for Plex plugin, but doesn’t specify which one)… I assumed it was from Catch because so many of the dates coincided with the dates of our last issue…

3) The Catch menu DOES only show the tv shows, and correctly. It’s just all this other stuff showing up…

It’s GOT to be another download feed for the other stuff - but I DO hope you can tell me how to make that “Link Type” stick.

BTW - I’m certain there’s no malware. My Mac is checked regularly (by hand - no background Norton or anything). I just have to see if there’s something else gobbling from the ‘net.

THANKS!!!

**Comment by mipstian** [comment]
It doesn't matter what shows in ShowRSS, as long as your feed address in Catch says "magnets=false". You can change it in the URL field in Catch if it's wrong, without even going to ShowRSS.

As for what the cause of your downloads is, I guess check your plex :) I don't know much about that. Maybe try keeping Catch close for a while and if you get another download, we can rule Catch out.

**Comment by SGans1** [comment]
OKAY! I get it - I'd forgotten that Catch had a setting independent from the ShowRSS setting. So, it looks like Catch's setting hadn't changed and still says "false", so I'm sorry to have bugged you - seems like Catch isn't the culprit. I've disabled a number of channels (plugins) in my Plex app to ensure they're not causing the issue. I'll keep messing with the Plex app to clear this issue up, as clearly, Catch is doing exactly as it should. I still have no idea why any other program started doing this, but clearly - it's another program!  clearly - it's another program! Thank you again for your help!

**Comment by mipstian** [comment]
Sure thing!
