### ISSUE TITLE
App never responds

### ISSUE THREAD

**Issue by john-catalano** [mipstian/catch#114]
Downloaded, added my showrss feed and clicked OK. Icon appeared in menu bar, but my cursor beach balled when I hovered over the icon. After several minutes, Activity Monitor still said that the app was "Not Responding". Any advice?

**Comment by mipstian** [comment]
This is new! Have you tried force quitting Catch from Activity Monitor and trying again?

**Comment by john-catalano** [comment]
Yes. At least three times now. Also tried restarting (my machine runs for days and days, so wanted to give that a shot).

**Comment by john-catalano** [comment]
Oooh! Something just happened. My torrents were downloaded after like four minutes following a restart. will monitor.

**Comment by mipstian** [comment]
Were they a lot?

**Comment by john-catalano** [comment]
About 10 different shows… no more than 12 total torrents.

**Comment by mipstian** [comment]
Ok that's totally manageable. Does it hang if you force a check via "check now"?

**Comment by john-catalano** [comment]
No, only for several minutes when it first starts.

**Comment by mipstian** [comment]
Does it still do that if you start it now?

**Comment by john-catalano** [comment]
Yep. Every time I start it, it hangs for a few minutes, whether I quit normally or forced quit.

**Comment by john-catalano** [comment]
Maybe not a FEW minutes.. but at least one minute.

**Comment by mipstian** [comment]
Can't think of a reason why that would happen.. Does it log something in Console.app when it hangs or when it unfreezes?
