### ISSUE TITLE
MacOS 10.6.8

### ISSUE THREAD

**Issue by elbow** [mipstian/catch#115]
Hi,

I'm forced to update due to the new ShowRSS and the discontinuation of hte Transmission Push.

But my old Mac Mini only has MacOS 10.6.8 and doesn't support newer versions.

If I fork Catch can you give me a heads up about the code that needs the new OS?

Thanks,
Steve

**Comment by mipstian** [comment]
Off the top of my head it's definitely the Notification Center stuff, and something with the power assertions (App Nap).

FYI you're not actually forced to update yet, as far as I know.

I'll keep this closed as it's not an active issue with Catch itself, but feel free to reply if you need anything else.
