### ISSUE TITLE
Catch is not compatible with new showrss

### ISSUE THREAD

**Issue by colomain** [mipstian/catch#118]
When you put a new generated url from new.showrss Catch says that is not a valid URL.

For example:
http://showrss.info/user/40937.rss?magnets=true&namespaces=true&name=null&quality=sd&re=yes

**Comment by mipstian** [comment]
Works for me, please make sure you're running the [latest version](https://github.com/mipstian/catch/releases/latest).

I'm assuming that URL is fake because it gets a 404, but it is accepted by Catch.

**Comment by colomain** [comment]
Sorry, I'm afraid I'm stuck in older version 1.6 (old Mac supporting only 10.7.5) . Sorry for wasting you time.

**Comment by mipstian** [comment]
Yeah, support for "new showrss" was added way after we dropped 10.7, sorry :(
