### ISSUE TITLE
Downloading .webloc files for the last two weeks

### ISSUE THREAD

**Issue by john-catalano** [mipstian/catch#120]
I've been using Catch successfully for several months. About two weeks ago, I noticed that new files were not showing up on an expected schedule. Checking my destination folder, I noticed that there were folders for the show names I'd subscribed to on showers.info, and in these folders were .webloc files and nothing else. It seems like I've been getting .webloc files instead of torrents/magnets for the last two weeks or so. When I double-click the .webloc files, Transmission.app starts downloading my file and my workflow continues as normal. An example .webloc file is attached.
[Maron 4x09 Shrink And Kink 720p.webloc.zip](https://github.com/mipstian/catch/files/331163/Maron.4x09.Shrink.And.Kink.720p.webloc.zip)

**Comment by mipstian** [comment]
Please check "open automatically". The setting was previously ignored for magnets.

**Comment by crashtestoz** [comment]
I have the same issue. All files get saved as *.weblog
I have checked "Open Automatically" but now nothing gets placed in the Watch folder. 
I am on Catch 1.9.4 (508)
