### ISSUE TITLE
Default to allowing Mac to sleep

### ISSUE THREAD

**Issue by danielcompton** [mipstian/catch#121]
I wonder if it would be more energy friendly to let Mac's sleep unless the user has explicitly selected for the Mac to stay awake. It was certainly unexpected to me that Catch was keeping my Mac awake, I see Catch like an RSS reader or Mail client, getting updates if it is on, but not preventing sleep.

Many people won't realise that Catch is what is keeping their Mac on, and use more power than necessary.

**Comment by mipstian** [comment]
True, however I think they'll be more surprised when they realize that the app "stops working after a while". If they want it to sleep, the fix is really simple, but by default the app should "work".

This was discussed at length here: https://github.com/mipstian/catch/issues/24
