### ISSUE TITLE
Option to look for x265 (HEVC) versions of programs?

### ISSUE THREAD

**Issue by gtwibell** [mipstian/catch#122]
The x265 (hevc) encoding method is being used for more and more TV shows at the popular Torrent sites. Shows encoded in this way are usually a quarter the size of equivalent x264-encoded programs and it has been adopted as the standard for 4K broadcasts. Any chance there could be an option in Catch to prioritise x265 encoded shows?

**Comment by mipstian** [comment]
That would be cool, but it's a feature request for ShowRSS, not Catch. Catch just gets whatever's in the feed.
