### ISSUE TITLE
Ability to save as torrent file or send request 

### ISSUE THREAD

**Issue by cylack** [mipstian/catch#123]
This is a feature request. I recently switched over to cloud based downloading using a service called seedr (www.seedr.cc). I have Catch set to not automatically download, but it saves the magnet links as webloc files which the seedr website does not recognize. If it is possible, to save as a torrent file or to to send the request to the seedr website or any cloud based service specified would be very useful. Thanks.

**Comment by mipstian** [comment]
Just go into ShowRSS and switch the feed to *not* use magnets, then use this new feed URL in Catch. Then Catch will save .torrent files.
