### ISSUE TITLE
Downloading .webloc files

### ISSUE THREAD

**Issue by crashtestoz** [mipstian/catch#126]
I have seen the previous closed post from July and I have done as instructed but I still have this problem.
All files get saved as *.weblog
I have checked "Open Automatically" but now nothing gets placed in the Watch folder. 
I am on Catch 1.9.4 (508)

**Comment by mipstian** [comment]
That's expected – Open Automatically means the magnet link will be opened on the fly, so no files will be written. Your default torrent client should have been launched and started downloading.

If you want to have torrent files in a folder, you should change your feed to not use magnets (but this is not recommended).

You can use the "recent episodes" window to re-open magnet links from your feed. When you do, your torrent client should be launched and start downloading.

Please reopen if this doesn't help!

**Comment by crashtestoz** [comment]
This used to work though and now stopped. Transmission on Qnap used to just pickup the files. now they are getting saved as webloc

**Comment by mipstian** [comment]
The behavior of "Open automatically" changed in version 1.9.4. Previously, it was ignored for magnet links (and worked as if it was always checked). Now it's respected. Whatever behavior you liked previously, you can have it back by checking "Open automatically".

**Comment by crashtestoz** [comment]
Thank you for the explanation. I just find it odd that even though I have not changed my setup in months, something changed.
