### ISSUE TITLE
Add Feature For Hiding Menubar Icon

### ISSUE THREAD

**Issue by richardzimmer** [mipstian/catch#131]
Option to hide icon from menubar completely. To reopen app window or app preferences; the user would just re-launch app, use customizable short-keys to open app window, or both...

**Comment by mipstian** [comment]
I forgot we already implemented this, even if it's not accessible via the UI :) This is requested rarely so I'm not sure it makes sense to have a setting in preferences, check out #44 and see if it works for you.

**Comment by richardzimmer** [comment]
I had no idea you could this from terminal. Learnt something new, and it totally works! Thank you so much!
