### ISSUE TITLE
Organize in folders by show name

### ISSUE THREAD

**Issue by MacLuke** [mipstian/catch#133]
So after url mirrors stopped working and getting "last update failed" error I switched to magnet links. Downloading is now working just fine but downloaded episodes are no longer organized in folders by their show name, they remain in their original folder instead.

![screenshot 2016-10-27 09 01 25](https://cloud.githubusercontent.com/assets/23093473/19757584/ff4b65b6-9c23-11e6-86b4-272b1aa953dc.png)

My Transmission setting is following

![screenshot 2016-10-27 09 04 20](https://cloud.githubusercontent.com/assets/23093473/19757676/622c06e0-9c24-11e6-8eb4-77caaa7c9974.png)

Could you please tell me if I am doing something wrong or if this an issue of Catch? Thank you

//and yes, I've already tried to reinstall both Transmission and Catch I do have checked the Organize in folders by show name option in Catch setting :)

**Comment by mipstian** [comment]
The organize setting doesn't work if you have magnet links and "open automatically". If you disable "open automatically" magnets will be organized in folders but saved as .webloc files that don't get picked up by Transmission watch, so you'll have to.. open them manually :)

**Comment by MacLuke** [comment]
Hello, thx for quick feedback. Is there any other solution that will remain
the possibility of automatic downloading and organizing? Like using
utorrent instead of Transmission maybe?

-- 
Lukas
Sent with Airmail

Dne 27. října 2016 v 10:10:38, Giorgio Calderolla (notifications@github.com)
napsal/a:

The organize setting doesn't work if you have magnet links and "open
automatically". If you disable "open automatically" magnets will be
organized in folders but saved as .webloc files that don't get picked up by
Transmission watch, so you'll have to.. open them manually :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mipstian/catch/issues/133#issuecomment-256575968>, or mute
the thread

**Comment by mipstian** [comment]
Not that I know of. But you can make up for the organization part by using a media player app that does that automatically regardless of folders. I use one called Infuse for example.
