### ISSUE TITLE
Beta is notifying constantly

### ISSUE THREAD

**Issue by zenspider** [mipstian/catch#135]
I'm running your beta to test out the new location logic... but every N minutes I get a notification that an episode has been downloaded. But I've already downloaded it (and it's still active so nothing happens). N minutes later (or if I manually check the feed) it happens again. and again.

**Comment by mipstian** [comment]
Good catch, should be fixed in alpha2: https://github.com/mipstian/catch/releases/tag/2.0-alpha2
