### ISSUE TITLE
RSS feed not valid

### ISSUE THREAD

**Issue by guille10k** [mipstian/catch#136]
I'm using Catch 1.6 on a Lion Macbook, but I'm getting that message about the not valid RSS every time I try to introduce the feed on the preferences.

The very same feed always worked on an other computer with Sierra.

**Comment by mipstian** [comment]
Hmm, does your feed URL start with "https"? HTTPS support came in 1.9.2

**Comment by guille10k** [comment]
Just checked. It starts with http. No s.

**Comment by guille10k** [comment]
This is what I get from the console

![captura de pantalla 2016-12-13 a la s 00 10 29](https://cloud.githubusercontent.com/assets/24532683/21120633/9f5b1056-c0c8-11e6-9458-c8d7a35f60b3.png)

**Comment by mipstian** [comment]
Can you post your URL here?

**Comment by guille10k** [comment]
http://showrss.info/user/76789.rss?magnets=true&namespaces=true&name=null&quality=null&re=null

**Comment by guille10k** [comment]
I tried all possible combinations switching Link type, Feed namespaces and Episode name style just in case, but it's always the same.

**Comment by mipstian** [comment]
Yeah, that's a "new ShowRSS" feed. Support for that came at a later version. Unfortunately there's no version that both runs on Lion and supports "new ShowRSS". If you can upgrade to Mountain Lion, you can get Catch 1.9.4 which will work.

**Comment by guille10k** [comment]
No way to have the old ShowRSS feed?

**Comment by mipstian** [comment]
Not that I know of, pretty sure they turned everything off after the transition period ended.

**Comment by theboyk** [comment]
Bummer. I'm stuck on Lion too. Can't use Catch anymore. 8(

**Comment by theboyk** [comment]
Anyone know any Catch alternatives that might work with Lion?

**Comment by guille10k** [comment]
Try Automatic 2. It works just fine and is simple. It has a period trial and then it's just 10€. Worth it. 

http://codingcurious.com/otomatic/
