### ISSUE TITLE
I use showRSS and Transmission on mac. The links no longer open automatically and instead I have to add them manually. In Transmission settings I use "Display window only when adding manually". Any suggestions why automatic download does not work?

### ISSUE THREAD

**Issue by Kyryacos** [mipstian/catch#137]
Make sure to do the following before submitting your issue - thanks!

- [ ] Make sure you're running the [latest release](https://github.com/mipstian/catch/releases/latest). You can find your version number at the bottom of the Help menu in Catch.
- [ ] [Check the FAQ](https://github.com/mipstian/catch/wiki/Frequently-Asked-Questions), your question might be answered there.
- [ ] [Check for an open issue](https://github.com/mipstian/catch/issues), and please comment on that issue instead of creating a duplicate.

**Comment by mipstian** [comment]
You know the things it says to do in the issue template? Do them please :)
