### ISSUE TITLE
Configuration?

### ISSUE THREAD

**Issue by Pazu** [mipstian/catch#141]
To eliminate the 404 errors as described, I changed my feed URL to use magnets, but still have Catch set to organize by folder. However, it's not clear to me how to set things up so the torrents still open automatically in Transmission. Am I missing something?

**Comment by mipstian** [comment]
It all depends on the "open automatically" setting. If that's on, with magnets, they will launch in Transmission as they come in. If it's off, magnets will be saved as .webloc files and can be double-clicked later. There's no way to use magnets and have folder organization like it worked with .torrent files.
