### ISSUE TITLE
Catch isn't automatically starting Transmission Requests

### ISSUE THREAD

**Issue by robwired** [mipstian/catch#142]
I've attached a screenshot of the options that I set in Transmission so that Catch could automatically start Magnet Torrents. Unfortunately a window appears for each torrent which requires user interaction.

I also tried unchecking the "Display a window when opening a torrent file" but that doesn't work either.

![showrss-transmission](https://cloud.githubusercontent.com/assets/1443811/24928868/ca586cf6-1eb8-11e7-820c-4878378a71c8.jpg)
<img width="544" alt="screen shot 2017-04-11 at 1 14 54 pm" src="https://cloud.githubusercontent.com/assets/1443811/24928897/e1d3105c-1eb8-11e7-946e-8fbf48f711d0.png">

**Comment by mipstian** [comment]
Are the Complete and Incomplete folders always reachable and writeable?

**Comment by robwired** [comment]
Yes, they are on a local drive, not a network share.

**Comment by robwired** [comment]
Buller? Anyone, anyone?

**Comment by mipstian** [comment]
At this point this is a question for the Transmission folks. But if you find out what it was, let me know so I can update the guide.
