### ISSUE TITLE
not getting new episodes

### ISSUE THREAD

**Issue by thejim** [mipstian/catch#143]
there's 2 new episodes showing up in showRSS but Catch isn't getting them.  I tried restarting Catch, restarting iMac running macOS 10.12.4, verified running latest version 1.9.4, checked Console and did not see the error message listed in FAQ. Was working fine up until today.

Here's output of Console after running Check Now:

Apr 26 21:31:44 Reality com.giorgiocalderolla.Catch.CatchFeedHelper[552]: Checking feed
Apr 26 21:31:44 Reality com.giorgiocalderolla.Catch.CatchFeedHelper[552]: Downloading feed http://showrss.info/user/8568.rss?magnets=true&namespaces=true&name=null&quality=sd&re=yes
Apr 26 21:31:44 Reality com.giorgiocalderolla.Catch.CatchFeedHelper[552]: Parsing feed
Apr 26 21:31:44 Reality com.giorgiocalderolla.Catch.CatchFeedHelper[552]: Parsed 43 files
Apr 26 21:31:44 Reality com.giorgiocalderolla.Catch.CatchFeedHelper[552]: Downloading files (if needed)
Apr 26 21:31:48 Reality xpcproxy[644]: libcoreservices: _dirhelper_userdir: 523: bootstrap_look_up returned 268435459
Apr 26 21:32:16 Reality Console[641]: BUG in libdispatch client: kevent[EVFILT_VNODE] monitored resource vanished before the source cancel handler was invoked
Apr 26 21:32:23 Reality com.giorgiocalderolla.Catch.CatchFeedHelper[552]: Checking feed
Apr 26 21:32:23 Reality com.giorgiocalderolla.Catch.CatchFeedHelper[552]: Downloading feed http://showrss.info/user/8568.rss?magnets=true&namespaces=true&name=null&quality=sd&re=yes
Apr 26 21:32:24 Reality com.giorgiocalderolla.Catch.CatchFeedHelper[552]: Parsing feed
Apr 26 21:32:24 Reality com.giorgiocalderolla.Catch.CatchFeedHelper[552]: Parsed 43 files
Apr 26 21:32:24 Reality com.giorgiocalderolla.Catch.CatchFeedHelper[552]: Downloading files (if needed)

Make sure to do the following before submitting your issue - thanks!

- [ ] Make sure you're running the [latest release](https://github.com/mipstian/catch/releases/latest). You can find your version number at the bottom of the Help menu in Catch.
- [ ] [Check the FAQ](https://github.com/mipstian/catch/wiki/Frequently-Asked-Questions), your question might be answered there.
- [ ] [Check for an open issue](https://github.com/mipstian/catch/issues), and please comment on that issue instead of creating a duplicate.

**Comment by mipstian** [comment]
Catch seems to think they have been downloaded already as it's not even trying to get them. Can you try clearing your history (https://github.com/mipstian/catch/wiki/Frequently-Asked-Questions) and see if that gets you the new ones?

**Comment by thejim** [comment]
Hi. Thanks for reply. A third episode became available and Catch got it just fine. I'm going to see if it continues to work before doing anything more. And I'm at work so can't do anything right now anyway 

Thanks!


Jim Kelley

**Comment by mipstian** [comment]
Ok, maybe the torrents themselves where the issue.

**Comment by thejim** [comment]
Hi

It did it again tonight so I cleared the cash like you suggested and that seems to have fixed the problem 

Thanks!


Jim Kelley
