### ISSUE TITLE
No downloads since January - this is June

### ISSUE THREAD

**Issue by SGans1** [mipstian/catch#144]
I'd been waiting to open the torrents for The Handmaids Tale, download and watch them - only to find that not only has that show never downloaded (ShowRSS says it has, but there's no sign of it on my computer), NONE of my other shows have anything new since January! (I often DVR, so this is a backup for most of what I watch, so I can watch elsewhere). 

Console FREQUENTLY shows that it's going out to look for the files, but I see that's produced nothing. Everything looks fine on ShowRSS... so what's happening here? Thanks!

**Comment by mipstian** [comment]
Did you do any of the things listed in the issue template?

**Comment by SGans1** [comment]
Yes, thank you for asking. I tried them ALL prior to writing... Unless missed something. But I'd first tried all my own thoughts, and then ensured I followed those too. Still no downloads.

**Comment by mipstian** [comment]
I don’t think the alphas would help with this specific issue, but they won’t hurt :)

Do you see the episodes you expect in the "Recent Episodes" window?

**Comment by SGans1** [comment]
Yes - annoyingly, I do see them in the "Recent Episodes" window - so I go looking all over my computer for them (thinking maybe they forgot where to download). No such luck - they just don't exist... 

So - now that you asked, I tried to look again. Now, remember there was NOTHING since January 11th in my TV Recordings folder. I look again today - and after messing with this - somehow at 3:14am, 2 versions of episode 09 TRIED to download - but they're .webloc files, not torrents (they even made their own folder, as requested). No previous episodes downloaded (and I have dozens of series on my RSS feed - none of THEM tried to download at all).

The ONLY thing I did when messing with this the other day was RE-enter my RSS feed address.

Wish I knew what happened on January 11th to change things in the first place!

I fear Alphas if I can avoid them. JUST switched to Sierra (finally), which is what made me look at all this in the first place... never want to add something that may de-stabilize a new OS, when I'm just trying to get it up and running with my apps......

**Comment by mipstian** [comment]
Torrent files are effectively dead, so the only thing we have are magnet links. If you have "Open automatically” unchecked, they will be saved as .webloc files which you can double-click to start the download. Otherwise, check it and.. the downloads will open automatically :)

As for the backlog, you were probably using a feed with magnets disabled (which wouldn’t have worked because .torrent files are dead).

I think this explains it, I’m closing but feel free to reply.

**Comment by SGans1** [comment]
I use the machine on which I'm working, so Open automatically would be terrible, since I teach software online. I can't check "Open Automatically". I don't have an alternate machine to use - this is my storage and server. 

When I click the webloc files, it opens Transmission, and gives me the warning as placed on my video at (https://1drv.ms/v/s!Ahg-Yg9KScG3gYsnlG7PDXlCewk0Lg). If I drag them to a browser, I get a dead page that opens my finder window and does nothing - it's like it's re-downloading the webloc file. :(

Also - NONE of my other feeds did anything at all. The "Recent Episodes" section says they're there, but they, unlike The Handmaid's Tale, didn't even create a folder of weblocs or add to their existing folders. Do I need to turn on Magnets for each feed? If that's the case, any idea how I can get those webloc files to actually do the automatic download as it should be?

So - since I can't use Open Automatically, does this mean that Catch and ShowRSS are going to be dead to me? That would make me really really sad.....

**Comment by SGans1** [comment]
ADDITIONAL - so, I tried again with opening with Transmission. It sat for a while with that error that says it needed a Torrent - but eventually started downloading - YAY! 

EXCEPT that I'm still not getting any downloads from my other feeds. Oh, and Magnet's been on all along. Never turned that off....

**Comment by mipstian** [comment]
Magnets used to be off by default way back then. And yes, when you open them in Transmission it takes a bit to start downloading because they’re magnets.

Catch only supports one feed, the one in the Preferences... not sure what you mean by “other feeds”?

**Comment by SGans1** [comment]
Sorry- wrong terminology - only one show coming down (the Handmaid's Tale) now - but my other shows on the feed aren't coming down.. (I'd turned on Magnets some time ago, based on a suggestion you'd made a ways back) See this image - all the shows that show they did work (Recent Episodes), vs the specified folder - sorted by date modified. Gotham and Lip Sync Battle should be up at the top, along with the Handmaids Tale that worked (I have lots of shows in my ShowRSS that haven't done anything since that January 11th date)

![screen shot 2017-06-07 at 6 01 55 pm](https://user-images.githubusercontent.com/17036634/26907873-93e39ffe-4bab-11e7-8f19-591f01ec9605.jpeg)

**Comment by mipstian** [comment]
You have an optimistic understanding of “date modified” for folders ;) Have you checked inside?

Btw you can redownload anything from the list with the little buttons in each row.
