### ISSUE TITLE
Save torrent files to folder not working

### ISSUE THREAD

**Issue by RoarSlot** [mipstian/catch#146]
Make sure to do the following before submitting your issue - thanks!

- [ ] Make sure you're running the [latest release](https://github.com/mipstian/catch/releases/latest). You can find your version number at the bottom of the Help menu in Catch.
 - running latest version 2.0 (524)

- [ ] [Check the FAQ](https://github.com/mipstian/catch/wiki/Frequently-Asked-Questions), your question might be answered there.
- did that

- [ ] [Check for an open issue](https://github.com/mipstian/catch/issues), and please comment on that issue instead of creating a duplicate.
 - no similar issue found

<img width="721" alt="screen shot 2017-09-17 at 10 11 07" src="https://user-images.githubusercontent.com/22563468/30519245-39aaaca4-9b91-11e7-813d-dedcb34d99a4.png">

**Comment by mipstian** [comment]
Added this to the FAQ, but to save you a trip:

This option is incompatible with magnets. Your torrent client will decide where the magnet link is downloaded based on its settings.
