### ISSUE TITLE
could not download

### ISSUE THREAD

**Issue by RoarSlot** [mipstian/catch#147]
Make sure to do the following before submitting your issue - thanks!

- [x] Make sure you're running the [latest release](https://github.com/mipstian/catch/releases/latest). You can find your version number at the bottom of the Help menu in Catch.
- [x] [Check the FAQ](https://github.com/mipstian/catch/wiki/Frequently-Asked-Questions), your question might be answered there.
- [x] [Check for an open issue](https://github.com/mipstian/catch/issues), and please comment on that issue instead of creating a duplicate.

**Comment by RoarSlot** [comment]
Hi,

Running latest version: 

Every "Check" results in:

default	10:34:44.851254 +0200	com.giorgiocalderolla.Catch.CatchFeedHelper	Could not download http://reflektor.karmorra.info/torrent/03C7321C229C1D510162D90DC998B39378EE8701.torrent: Error Domain=com.giorgiocalderolla.Catch.CatchFeedHelper Code=-7 "Could not download torrent file (bad status code 404)" UserInfo={NSLocalizedDescription=Could not download torrent file (bad status code 404)}
default	10:34:44.851658 +0200	Catch	Feed Helper error (checking feed): Error Domain=com.giorgiocalderolla.Catch.CatchFeedHelper Code=-7 "Could not download torrent file (bad status code 404)" UserInfo={NSLocalizedDescription=Could not download torrent file (bad status code 404)}

**Comment by mipstian** [comment]
Please actually check the FAQ, don’t just check the box mmkay? :)

**Comment by RoarSlot** [comment]
You are right, sorry.

So that means, I am in a bind, as I can only download using magnets, but then I cannot save to a folder :-)

**Comment by mipstian** [comment]
You can setup a download folder in your torrent client. The thing that doesn’t work is having each show go to its own subfolder.

**Comment by mipstian** [comment]
Or if you meant save the .torrent files, you only will be able to save the magnet links as .webloc files. But you won’t be able to save .torrent files because they do not exist :)

**Comment by RoarSlot** [comment]
Exactly, that is the issue for me.
