### ISSUE TITLE
Question about system sleep setting

### ISSUE THREAD

**Issue by bambamra1** [mipstian/catch#148]
Hi,

this might be a dumb question, and I'm sorry if it is, but I need some explanation on how "Prevent system sleep when active" works. In this context, what exactly does "active" mean?

Suppose I have Catch running in the background, all time, every time, and not turned on the setting "Only check feed between (...)". Will my computer ever go to sleep? Or if I do have the setting "Only check feed between (...)" turned on, does that count as "active" time, and will it go to sleep at times that are not covered? (e.g. check feed between 0:00 and 8:00 means that system sleep is prevented from 0:00 to 8:00, but not from 8:00 to 0:00).

**Comment by mipstian** [comment]
Not a dumb question, I actually struggled with the wording here. But in short, "Active" means "not paused".

In both the example scenarios you provided, the mac will not sleep.

**Comment by bambamra1** [comment]
Thank you!
