### ISSUE TITLE
Can't get a valid URL from showRSS

### ISSUE THREAD

**Issue by tjluoma** [mipstian/catch#154]
I've read <https://github.com/mipstian/catch/wiki/Configuration> but I still can't get a valid URL from showrss.info. I have <http://showrss.info/user/182812.rss?magnets=true&namespaces=true&name=null&quality=null&re=null>

Here's a screenshot of my settings:

<img width="991" alt="showrss-info" src="https://user-images.githubusercontent.com/26965/44303276-91727d00-a30a-11e8-9e36-90d292909267.png">

I'm using the latest version of Catch.app as far as I know:

	CFBundleShortVersionString: 1.9.4
	CFBundleVersion: 508

Can you tell me what I'm doing wrong?

Thanks

**Comment by mipstian** [comment]
That URL **is** valid, so I think the problem is the copying it into Catch part. Try right clicking and using Copy Link.
