### ISSUE TITLE
Catch appears to be connecting to cox?

### ISSUE THREAD

**Issue by Beasta** [mipstian/catch#155]
Little snitch seems to indicate that Catch is connecting to cox.com?

[Screenshot](https://www.dropbox.com/s/p7agp2pygthv4w7/Screenshot%202018-09-13%2010.53.41.png?dl=0)

Make sure to do the following before submitting your issue - thanks!

- [x] Make sure you're running the [latest release](https://github.com/mipstian/catch/releases/latest). You can find your version number at the bottom of the Help menu in Catch.
- [ ] [Check the FAQ](https://github.com/mipstian/catch/wiki/Frequently-Asked-Questions), your question might be answered there.
- [ ] [Check for an open issue](https://github.com/mipstian/catch/issues), and please comment on that issue instead of creating a duplicate.

**Comment by mipstian** [comment]
I bet ShowRSS was down for a sec and your provider intercepted that and sent you to one of their pages. Is Cox your ISP?

**Comment by Beasta** [comment]
yeah i bet thats correct. Thanks
