### ISSUE TITLE
Catch 1.9.4 keeps adding multiple instances of itself to Login Items on my user account

### ISSUE THREAD

**Issue by timbck2** [mipstian/catch#159]
I haven't yet figured out what triggers it, but I'm always finding more then one instance of Catch in Login Items on my user account. I delete the extra one(s), then check again sometime later and there's another one added. This is with the latest release version of Catch 1.9.4.

I do plan to install the latest alpha version to see if it's still happening.

**Comment by timbck2** [comment]
OK, I found what triggers it. If I remove the extra instance in Login Items, quit catch, and then launch it again, a second instance is added. I've seen more than two in the past, but it appears to be stopping with two. Attached is a screen shot showing more than one instance.

<img width="668" alt="catch issue 159" src="https://user-images.githubusercontent.com/1268450/52523270-e0abc180-2c4c-11e9-9e49-9c45db85f2c9.png">

**Comment by timbck2** [comment]
I tested Catch 2.0 alpha 4, and the problem seems to be gone. It has only added one instance of itself to my Login Items.

**Comment by mipstian** [comment]
I think the problem is you don’t know which ones are the “extras”. You can quit Catch, delete them all, and then launch Catch to have it re-add itself there. There should only be one instance from that point on.
