### ISSUE TITLE
Use user identification

### ISSUE THREAD

**Issue by adrinavarro** [mipstian/catch#16]
Most user issues come from picking a bad feed (a few mails a day), and now that everything's changing with multiple feeds to choose from and magnets yes/no, integrating user auth in Catch could be a good idea.

It's very basic, but it can be done: http://showrss.info/static/api.txt

Ask for the username and password in a dialog, log in (validate and store user_id), build your own feed address depending on the settings (magnets? folders?), put a button to "log out" (forget user_id). Pretty simple for the user, maybe some amount of work on the code side. It's a nice improvement, it can wait, though.

**Comment by mipstian** [comment]
@adrinavarro is this still a thing? The link above is broken
