### ISSUE TITLE
Old version reading rss

### ISSUE THREAD

**Issue by yingtongbob** [mipstian/catch#160]
I have a seedbox that only support up to OSX 10.6 = Catch 1.5.
Did the ShowRSS feed link change that it does not read in old version ?
http://showrss.info/user/xxxxx.rss?magnets=true&namespaces=true&name=null&quality=null&re=null
Get feedurl not valid

**Comment by mipstian** [comment]
Yeah, 1.6 added support for the new URLs. You can see what's changed here: https://github.com/mipstian/catch/releases?after=1.9.1

(sorry I missed the notification for this issue)
