### ISSUE TITLE
App seems to close overnight

### ISSUE THREAD

**Issue by 12thDegree** [mipstian/catch#171]
Hi, 
I checked the issues, but didn't check the FAQ. 

OS X 10.15.7 (19H114)
Catch 1.9.4 (508)

Seems the app is closing on its own when I leave it open for a day or more. Never noticed this behaviour until after I updated my Mac to 10.15

Just wanted to pass this by you, in case you had a quick idea. 

cheers, 

Kevin

**Comment by mipstian** [comment]
Do you see any crash logs in Console.app?

**Comment by 12thDegree** [comment]
Hi there, 

I don’t see any logs in the Crash Reports section of my Console.app
I also tried searching “catch” in all messages, as well as errors and faults and couldn’t find anything. 

KEVIN CROOK
647 806 3540
crook12kevin@gmail.com

**Comment by mipstian** [comment]
Well the app never closes itself, so if it's not a crash... Maybe some other process on the system is closing it?

**Comment by 12thDegree** [comment]
Yeah, it’s a mystery to me. I can’t find anything innocent in console either. 
I booted around on Google for a bit, my best guess is that the macOS High Sierra might be closing certain apps during sleep because it thinks it’s a good idea.

Thanks for the help, 

Kevin

**Comment by mipstian** [comment]
Doesn't seem like a Catch issue, so closing for now.
