### ISSUE TITLE
Catch 2.0 don't work on El Capitan

### ISSUE THREAD

**Issue by alexandremjacques** [mipstian/catch#176]
Catch 2.0 wouldn't work after the update (clicking the app doesn't produce any results; no app on the task bar, no process in activity monitor).

Tried redownload and start from Applications folder, no error and no application running either.

macOS 10.11.6

**Comment by jonnycc** [comment]
I have the same issue. 
MacOs 10.11.6
the message that comes up for me in console is as follows:
(com.apple.xpc.launchd.oneshot.0x10000004.Catch[6140]) Service exited due to signal: Segmentation fault: 11

downgrading to previous version works.

**Comment by mipstian** [comment]
Can you send me the crash report? It should be in Console as well.

**Comment by jonnycc** [comment]
no problem . i have attached. 
[Catch_2021-04-14-151306_helper.crash.zip](https://github.com/mipstian/catch/files/6320939/Catch_2021-04-14-151306_helper.crash.zip)

**Comment by mipstian** [comment]
So after examining the crash report, it's clear this is related to the app adding itself to the login items.

Not sure why it's failing, but all of those APIs are deprecated, so I was thinking of deleting that functionality altogether anyway. And then replacing it with a link to a help page that explains how to add Catch to your Login Items manually (you just drag and drop the app to the Login Items list in your user in System Preferences->Users and Groups).

Sounds good?

**Comment by mipstian** [comment]
I've uploaded an alpha with the functionality removed:
https://github.com/mipstian/catch/releases/tag/2.0.1-alpha1
Please check it out and let me know if everything's working!
I'll add the aforementioned instructions before release.

**Comment by jonnycc** [comment]
Great work. 
that version opens and everything appears to check out. 
it was already added to the login items. (I am assuming from the older version?)
thanks

**Comment by mipstian** [comment]
Yup, the login item from earlier versions wouldn't go away on its own.

**Comment by mipstian** [comment]
Fixed in https://github.com/mipstian/catch/releases/tag/2.0.1
