### ISSUE TITLE
Webloc instead of magnets on Big Sur

### ISSUE THREAD

**Issue by djjoelyd** [mipstian/catch#177]
Since the upgrade to 2.0 on BigSur. Catch is not adding the magnet files to my torrent app. Instead its downloading a webloc file.

e.g. Batwoman S02E10 WEBRip x264 ION10.webloc

I have checked the feed, version, re-installed. Still nothing.

**Comment by mipstian** [comment]
Do you have "Open Automatically" checked?

**Comment by djjoelyd** [comment]
No? Where would that be?
