### ISSUE TITLE
Repeated downloads of the same torrents

### ISSUE THREAD

**Issue by Kudusch** [mipstian/catch#179]
Since the update to v 2.0 Catch keeps downloading the same two torrents. In the Recent Episodes window the torrents are not shown at all and they don't seem to be duplicated in the RSS feed. I recently uninstalled and reinstalled the app.

I am running version 2.0.1 (720).

**Comment by mipstian** [comment]
Hi!
Did you ever restart the Mac since?

**Comment by Kudusch** [comment]
Sorry for responding so late! I restarted (and updated) the machine since then a couple of times and I am on the current version of Catch.

Every time I quit and start the app, I get a notification that a new episode was added. It's always the latest two episodes. This only occurs with a specific show and when I remove the show from ShowRSS, the problem is gone.

**Comment by mipstian** [comment]
Closing in favor of #180, seems to be the same issue.
