### ISSUE TITLE
Downloading the same torrents multiple times

### ISSUE THREAD

**Issue by thagorastos** [mipstian/catch#180]
After the latest updates to Catch 2.0 and 2.0.1, the app keeps downloading the torrents from my feed multiple times. No matter if I leave the files where they are downloaded or delete them, it keeps downloading them again and again every time it checks for updates. Is this an intended function?

Versions prior to 2.0 were working properly.

**Comment by mipstian** [comment]
Hi!
Did you ever restart the Mac since?

**Comment by thagorastos** [comment]
This was my thought too. I did restart it a few times, but nothing changed. I also tried killing the app to make sure it does not run and ran it manually. Same result. Could you point me to the folders where the app stores its configuration? Maybe deleting the configuration could solve this.

Additional note: reverting the app version prior to 2.0 (from a backup) makes it work properly, so it must be something that has changed in the new version.

**Comment by mipstian** [comment]
Issue #178 had the same symptoms, and the user managed to fix it by deleting a bunch of files. I'd be nice to know what exactly fixes the issue though!

The helper's sandbox container has everything the helper can touch (but as far as I know, nothing is in there):
~/Library/com.giorgiocalderolla.Catch.CatchFeedHelper/
The main app's preferences are here:
~/Library/Preferences/org.giorgiocalderolla.Catch.plist

I don't think there's anything else. If you delete the preferences file, of course, all of the app's settings will be lost.

**Comment by Kennjon** [comment]
Have the exact same issue

**Comment by mipstian** [comment]
> I've been having the same issue too. Any other ideas as to what I can try?

Yeah, they're in my previous message 😅

**Comment by Kudusch** [comment]
Same issue and deleting the files like #178 suggested did not fix it for me.

**Comment by mipstian** [comment]
Should be fixed in https://github.com/mipstian/catch/releases/tag/2.0.2

Thanks for all the help!

**Comment by tomcat335** [comment]
Thanks for fixing it!

Dan
