### ISSUE TITLE
Catch doesn't download automatically.  

### ISSUE THREAD

**Issue by rolfmblindgren** [mipstian/catch#186]
Make sure to do the following before submitting your issue - thanks!

- [X] Make sure you're running the [latest release](https://github.com/mipstian/catch/releases/latest). You can find your version number at the bottom of the Help menu in Catch.
- [X] [Check the FAQ](https://github.com/mipstian/catch/wiki/Frequently-Asked-Questions), your question might be answered there.
- [X] [Check for an open issue](https://github.com/mipstian/catch/issues), and please comment on that issue instead of creating a duplicate.

Catch doesn't download automatically.  I'm on the last version, compiled myself. It used to work … 

![Screen Shot 2021-05-21 at 19 40 12](https://user-images.githubusercontent.com/2772675/119177349-7e1d0f00-ba6c-11eb-9d8c-cdc82bcf0639.png)

**Comment by mipstian** [comment]
There's only two reasons for the `Skipped` status, both user-fixable:
1) The `Save to:` folder from `Preferences` is missing not writable (if you build yourself, you might need to re-select it and give permission)
2) You have no feeds in `Preferences`
