### ISSUE TITLE
App is failing to retreive any RSS feeds

### ISSUE THREAD

**Issue by cparrey** [mipstian/catch#188]
The app is failing to retrieve any feeds, this is from multiple sources including showrss and some other pages I have set up.

Make sure to do the following before submitting your issue - thanks!

- [ X] Make sure you're running the [latest release](https://github.com/mipstian/catch/releases/latest). You can find your version number at the bottom of the Help menu in Catch.
- [ X] [Check the FAQ](https://github.com/mipstian/catch/wiki/Frequently-Asked-Questions), your question might be answered there.
- [ X] [Check f
![Screen Shot 2021-06-29 at 9 58 43 am](https://user-images.githubusercontent.com/27956497/123717638-992b3c00-d8c0-11eb-9aab-5a357e8356f3.png)
or an open issue](https://github.com/mipstian/catch/issues), and please comment on that issue instead of creating a duplicate.

**Comment by mipstian** [comment]
Console.app will tell you what the issue is (mostly likely something wrong with the non-showrss feeds). Please reopen if the error message isn't enlightening enough.
