### ISSUE TITLE
Catch not getting latest shows from ShowRSS

### ISSUE THREAD

**Issue by dywang56** [mipstian/catch#189]
I have the latest version of Catch and am running on Big Sur 11.6.  Have been using Catch to feed Transmission for many years with no issue.  Stopped working on 9/30 and hasn't worked for a few days now.  I can still download via Transmission if I find the torrents manually.  Check Now on Catch doesn't return anything new but I can see that the last date of Recent Episodes was 9/30.  Any thoughts?

Make sure to do the following before submitting your issue - thanks!

- [ ] Make sure you're running the [latest release](https://github.com/mipstian/catch/releases/latest). You can find your version number at the bottom of the Help menu in Catch.
- [ ] [Check the FAQ](https://github.com/mipstian/catch/wiki/Frequently-Asked-Questions), your question might be answered there.
- [ ] [Check for an open issue](https://github.com/mipstian/catch/issues), and please comment on that issue instead of creating a duplicate.

**Comment by cyclism6486** [comment]
Same here (except I'm running 10.14.6) - worked fine for years, but last shows found were 9/30 and several have been available since then.

**Comment by inezduff** [comment]
I have the same issue, also on Big Sur 11.6. I can't even add torrents manually from showrss.

**Comment by mipstian** [comment]
ShowRSS was down...

**Comment by dywang56** [comment]
Thank you!
  
  
  
  
___
  
  
Douglas Wang
   +1.216.577.9768 (tel:+1.216.577.9768)
  ***@***.*** ***@***.***)   
      
  

  
  
>
