### ISSUE TITLE
Russian Language

### ISSUE THREAD

**Issue by yevgenyloginov** [mipstian/catch#192]
I've made a 95% translation and I have one question before completing it. 

What does "Organize in folders by show name" mean? I have this box checked but I can't see any effect. Is it supposed to automatically create folders with feed names on my HDD and rearrange the downloaded content into them?

I need to get this clearly in order to translate.

**Comment by mipstian** [comment]
It creates folders named after each show and downloads the torrent files in there. Thing is, it doesn't work with magnet links, so today it's near-useless.

**Comment by yevgenyloginov** [comment]
Looks like it's done then. 

[Localizable (Russian).strings.zip](https://github.com/mipstian/catch/files/7802263/Localizable.Russian.strings.zip)

**Comment by mipstian** [comment]
Thanks, I've integrated this in the code!
