### ISSUE TITLE
Last Update (Failed)

### ISSUE THREAD

**Issue by andrewrgossett** [mipstian/catch#194]
after several restarts and reinstalls it keeps reading as failed. 

Make sure to do the following before submitting your issue - thanks!

- [ ] Make sure you're running the [latest release](https://github.com/mipstian/catch/releases/latest). You can find your version number at the bottom of the Help menu in Catch.
- [ ] [Check the FAQ](https://github.com/mipstian/catch/wiki/Frequently-Asked-Questions), your question might be answered there.
- [ ] [Check for an open issue](https://github.com/mipstian/catch/issues), and please comment on that issue instead of creating a duplicate.

**Comment by mipstian** [comment]
What's the feed? You're giving me nothing to work with here :/

**Comment by andrewrgossett** [comment]
sorry, I should have gone back to delete my post, it was Yify, the feed wasn't updating.  when the first one failed they all paused. im just an idiot that didnt understand how it worked.
