### ISSUE TITLE
Automatic downloading of torrent files creates invalid torrent

### ISSUE THREAD

**Issue by joshkerr** [mipstian/catch#198]
I'm running the latest version 2.3 on a fully patched Mac OS 12.5.

I'm using ShowRSS with the legacy feed URL option and namespaces for catch support. 

I'm using a program called watchexec which is looking at my Downloads folder for torrent files. When Catch automatically downloads torrent files from the feed, it ends up with corrupted or invalid torrent files. When I open the "Recent Episodes" screen and choose to redownload the show, it works fine.

**Comment by mipstian** [comment]
Both are handled in the same way, so I'd say that's probably a server issue. Example: the feed contains torrent URLs that aren't properly mirrored yet, and when Catch tries to download that URL it gets an error webpage instead. Should be pretty easy to verify this by opening the "corrupted" .torrent file in a text editor or similar. Please let me know if this checks out, closing for now.

P.S. Sorry, I didn't get notifications for this issue :/
