### ISSUE TITLE
Don't check unless on specified network

### ISSUE THREAD

**Issue by boutcher** [mipstian/catch#37]
Some people may not want to have Catch checking for new shows unless they're on an active VPN connection, or maybe at home and not at work, etc. So this request is for some option like:

[ x ]  Only check when connected to the following network(s): [  0.0.0.0/0 ] 

Then, if my ISP owns a class C network 100.150.200.0, I would check the box and enter "100.150.200.*" or CIDR "100.150.200.0/24"... Whatever is easiest you think for the population to configure.

Before every fetch of the RSS feed, hit some web service somewhere like whatsmyip.com or something, and ensure you're on a specified network.   If you are, you continue as normal. 

If NOT, don't poll for new files, and maybe change the icon to one with a pause symbol or something on it....

**Comment by mipstian** [comment]
You know what, I think this isn't worth it. Sorry @boutcher, thanks for the suggestion anyway!
