### ISSUE TITLE
Ability to handle multiple arbitrary rss feeds

### ISSUE THREAD

**Issue by mipstian** [mipstian/catch#4]
Reported by josebiro, Jul 17, 2010
Ability to handle multiple arbitrary rss feeds

This didn't make 1.0 but will definitely come in the future.
The main problem here is how to make clear that regular feeds do not support stuff like folders, etc..
Status: Accepted 

Automatically creating folders is out the window, but ideally when adding such feeds you could specify where catch should download them to.

Yep, per-feed download targets would be nice and easy to implement.

If you know someone who develops for the Mac, please ask him/her to join the project. There are many good feature request but I just don't have time on my hands right now.

Contact me: ronmcasey@gmail.com

I'd like to see Catch accept feeds from sites other than showsRSS.  If the feeds are formatted the same, is there any reason why it wouldn't work?

@dawalsh no, there's not. As I said before, though, there's a little UI design work - which I love, by the way - needed in order to create UI that can easily support both formats but makes it clear that advances features such as "Organize torrents in folders by show name" are only possible with ShowRSS feeds.

Problem is, I don't have lots of time on my hands now. And being this an open-source project, I hoped someone else would join and help us with code. If you know some Cocoa developers by all means ask them!

**Comment by brandbrilliance** [comment]
Supporting maybe MORE than just RSS feeds. People could remotely add simple items, e.g.

I also have a local script that will run off the crontab and  look for a remote public URL file, e.g. Google Doc / FTP / Dropbox URL  and download a data content in it

Basically the data file content looks like this and I just scrub the part before the pipe and check it against previous loads. 

```
magnet:?xt=urn:btih:f28b6fd9f0506cc3feb3f21124ee340ce3279704&dn=Magnet_1-QPEL%5Beztv%5D.mkv%5Beztv%5D&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A80&tr=udp%3A%2F%2Fglotorrents.pw%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969 | Magnet 1
http://link.com/D535BA4E81381859FA35E73676505695CC12C5E5.torrent | Torrent 1
http://link.com/775AC6C860CAB18CD8A538389AACB4AC583185E0.torrent | Torrent 2

```

**Comment by mipstian** [comment]
@brandbrilliance don’t feel like coming up with a new standard for feeds :) it’s not at all hard to convert that to rss...

**Comment by mipstian** [comment]
Done in alpha 5 https://github.com/mipstian/catch/releases/tag/2.0-alpha5
