### ISSUE TITLE
Nicer names for torrent files

### ISSUE THREAD

**Issue by psaintemarie** [mipstian/catch#40]
Hi,

Nice enhancement would be those two following:

- Catch already organize by Shows name creating folders, it would be nice to have "Seasons" subfolders inside of them.
- Could it be possible de rename the .torrent files with a much nicer name like "Show.s0Xe0X.QUALITY.format", something already seen in TVShows app.

Great piece of software combined to showRSS, keep up the good work.

Thanks.

**Comment by maccouch** [comment]
hi. can i add +1 to the nice torrent names feature? hugely useful for me as i don't like the having tranmission automatically downloading stuff, i prefer to just have the torrent downloaded and then, with a simple click adding them. this way i can monitor the shows i watch and not having my disk space fully consumed by shows when i'm don't have the time to see them. (hypothetically of course...)

**Comment by mipstian** [comment]
Thanks for the use case @maccouch!
