### ISSUE TITLE
Saving Episodes in Season Folders

### ISSUE THREAD

**Issue by aristako** [mipstian/catch#49]
Hi! Firstly, great, clean app! Really efficient :-)

Was wondering how easy it would be to implement a feature to further organise media downloaded into separate season folders within the show folders (i.e. ShowName > Season1 > Episode1).

Keep up the good work! :-)

**Comment by showrss** [comment]
Hmm, the database does hold structured data but there isn't a well-defined way of structuring it. It varies between day shows (ie. Colbert Report), specials, season specials, multi-episode (S01E21E22), so a XML representation is feasible but as far as I know there's no standard yet.
