### ISSUE TITLE
Feed not updating

### ISSUE THREAD

**Issue by gatogatogato** [mipstian/catch#53]
Just recently I realized that Catch does no longer update my ShowRSS feed. I could not determine the reason why as I only get the error message in the dropdown menu.

**Comment by mipstian** [comment]
Hi, sorry it took me so long to reply.
Still experiencing this? Try getting a new feed url from showrss, and if that doesn't work check what is printed out in Console.app and paste it here!

**Comment by gatogatogato** [comment]
Thanks for the  reply - meanwhile this phenomenon seems to be gone. I will let you know if it comes back.

**Comment by mipstian** [comment]
There are hiccups with showrss or what it depends on sometimes. Let me know if this happens again!
