### ISSUE TITLE
Growl notifications

### ISSUE THREAD

**Issue by nicholasgodoyx** [mipstian/catch#55]
I used another program to watch my ShowRSS feed but catch is much more reliable, so I switched. I love it, but the only thing I miss is Growl notifications, because I used it to notify my phone via Boxcar 2 whenever a new episode was being downloaded.

**Comment by mipstian** [comment]
Groan.. I was so happy to drop the Growl dependency :) I really don't wanna bring that back :/
I have a couple ideas:
1) If you torrent client uses Growl, you can get notified via Boxcar when an episode finishes downloading, which is an even better notification :)
2) You could fork this to support Growl - the surface area for the notification stuff is tiny, so it would be pretty simple.
We dropped Growl a long time ago and this is the first time I've heard anything about it..
