### ISSUE TITLE
Command Line Support

### ISSUE THREAD

**Issue by nicholasgodoyx** [mipstian/catch#56]
I would really appreciate it if you could add a way of searching for new shows via command line, because I want to automate my computer in a way that every day at 4AM it wakes up, checks for tv shows, and then go back to sleep after one hour. I don't see a way of doing that without command line support...

**Comment by mipstian** [comment]
What about launching Catch at 4am and killing it at 5am? You can pretty easily get this done via the command line.

**Comment by mipstian** [comment]
Closing (stale), reopen if needed.
