### ISSUE TITLE
Auto-starting magnet torrent download

### ISSUE THREAD

**Issue by Pazu** [mipstian/catch#57]
If I use Catch with Transmission, and am using magnet torrents from ShowRSS, is there a way to make Transmission auto-start the download? I have unchecked "Display a window when opening a torrent file" in Transmission, but Transmission still displays a window prior to starting the download.

Also, again using magnets, will Catch tell Transmission where to save the completed file (e.g., in the folder for the show name and season)?

**Comment by mipstian** [comment]
Dupe of #52, please refer to the discussion there and reopen if needed.
