### ISSUE TITLE
HTTPS ShowRSS URLs don't work

### ISSUE THREAD

**Issue by Pazu** [mipstian/catch#58]
If I use an HTTP feed URL from ShowRSS which works in Catch, and change the protocol from http to https, Catch shows the yellow exclamation point to the right of the “Feed URL” field, though the https feed URL works fine in a browser.

**Comment by mipstian** [comment]
@leonklingele already fixed it in d1923ec1067eca6de6e3f9cd835879f147e5dbb7, but I didn't get around to doing a release yet. You can build from master, or just wait for the next release :)

**Comment by Pazu** [comment]
@mipstian Any plans for a 1.9.2 release in the future, near or otherwise?

**Comment by mipstian** [comment]
Err.. whoops, I kinda forgot. Let's see if I still remember how to do this.

**Comment by mipstian** [comment]
@Pazu i've released 1.9.2, could you try it out and confirm everything works as you'd expect now? Thanks!

**Comment by Pazu** [comment]
@mipstian It (HTTPS) appears to be working great. Thanks for the release!

**Comment by mipstian** [comment]
Great, thanks for reporting!
