### ISSUE TITLE
Organize in folders by show name.

### ISSUE THREAD

**Issue by molonlabe88** [mipstian/catch#60]
Downloads are not being organized in any method. I have the box checked.

**Comment by mipstian** [comment]
Are you using magnet links? That option only works if you're not.

**Comment by molonlabe88** [comment]
I'm using both and I have transmission just start them without asking me, so I don't know if the ones they downloaded are magnet links or not. But I guess they probably are since it isn't working.

If I turn off magnet links, what kind of effect will that have on quality/speed etc...?

**Comment by mipstian** [comment]
Downloads will take a bit less time to start since there's no magnet metadata to download, and you'll find a few torrent files in the trash :)

**Comment by molonlabe88** [comment]
So you run yours with magnets turned off?

**Comment by mipstian** [comment]
No I use magnets, but I don't care about organization. File names are enough for me, and the files are short lived.

**Comment by molonlabe88** [comment]
Ha, ok. I never cared before I cut the cord, no reason to start now. Thanks for the insight though, at least if I change my mind I know how to fix it.
