### ISSUE TITLE
Catch - Not a Valid torrent

### ISSUE THREAD

**Issue by brick1234** [mipstian/catch#64]
I have been trying to get Catch (1.9.2) to work on my mac (OS X 10.10.3) for some time now with no luck at all.  have searched for somewhere to read something on what I am doing incorrectly but I can not find anything, or nothing new that I already had tried.  I have catch some what working in that it tells me new episodes are added, but thats it.  Transmission (2.8.4).  I have double checked my showrss feed too.  It is also good.  Transmission won't even load the torrents.  I have to check the "recent episode" list in Catch and then re-download them only to get the follow message.

![transmission error](https://cloud.githubusercontent.com/assets/12521336/7717515/15348a46-fe60-11e4-9ded-ab91697691aa.png)
which states :
"etc.ch.html.torrent" is not a valid torrent file.  The torrent file cannot be opened because it contains invalid data.

any help here would be great.  I am not sure what to do or where to look.  Even a nudge in the correct direction would be great

Drew

PS. after writing this I did read all of the current issues, none of which I found an answers for, Thanks in advance

**Comment by mipstian** [comment]
I think that's because eztv is dead - @showrss would know more about that. Probably temporary anyway.

**Comment by mipstian** [comment]
Closing, seems resolved. If not, let me know.
