### ISSUE TITLE
ShowRSS link not accepted

### ISSUE THREAD

**Issue by yosoymilk** [mipstian/catch#65]
Can't make the app accept my link, have tried every format that ShowRSS provides.
Note: not my actual user ID

![screen shot 2015-06-01 at 21 17 56](https://cloud.githubusercontent.com/assets/12703012/7922381/bc4dbfb2-08a3-11e5-9b36-075bce2e0bd9.png)

**Comment by mipstian** [comment]
Yup, you're missing some parameters. Just follow the guide https://github.com/mipstian/catch/wiki/Configuration
