### ISSUE TITLE
Option to delay new episode download

### ISSUE THREAD

**Issue by ledge74** [mipstian/catch#67]
Hello. First thanks for this great app! 

I use [filebot](http://www.filebot.net) to manage my torrents once downloaded, and also to automate subtitles downloads. However, subtitles are most ofter available a few hours after the original torrent has been released.

It would neat to have an option to delay the download of the episodes, for example : delay the download of 2 / 3 / 6 / 12 / 24 hours

Thanks :)

**Comment by mipstian** [comment]
Hi, thanks for the kind words!

FileBot sounds cool, I'll check it out if the need arises.

Your solution seems backwards to me though - you have no reason to delay downloads in Catch. All you need to delay is checking for subtitles. I don't like the arbitrary delays either, they're just magic numbers and I can't expect users to know them in advance, right?

Wouldn't it be loads better if FileBot would poll for subtitles every hour or so until it found something? I think changing Catch to accommodate this would result in a hacky compromise.

**Comment by ledge74** [comment]
Hi mipstian, thanks for the reply. You're right, I'll investigate how I can efficiently delay the download of new subtitles, it makes more sense like this!
