### ISSUE TITLE
El Capitan (Public Beta): Cannot successfully select a download directory on SMB/AFP share

### ISSUE THREAD

**Issue by azurecrash** [mipstian/catch#68]
Hi! Awesome app. Thought I'd make you aware of an issue I ran into last night on El Cap -- and it could be on the OS X side -- but none the less...

I have a NAS drive that shares out via AFP and SMB. SMB for PVR related things and AFP for Time Machine only. The drive auto mounts on boot.

In Catch, trying to set the download directory to a directory on this drive fails via the standard Finder that appears for folder selection. For whatever reason, Catch will not allow me to browse into the shared drive and the Finder window notes that I'm connected as a guest even though the drive is mounted to the system at login. Would a second mount operation be initiated during this browsing session? Odd and unexpected.

Now, if I separate open a Finder window, browse to the root folder where the desired download directory is sitting, and DRAG that desired target onto the directory widget in Catch which shows the icon and name of the download directory, Catch behaves as expected and downloads to the shared drive.

**Comment by mipstian** [comment]
Yeah pretty sure this is on OSX. All I'm doing is telling the system to open a standard file open sheet, what goes on in there is entirely handled by the OS - I just get a URL back.

If you see this in system apps or other third party apps as well, or can create a tiny example app to demonstrate the issue, I recommend filing a bug with Apple.
