### ISSUE TITLE
El Capitan (Public Beta): TV show folders not created if initial Catch downloads are stopped

### ISSUE THREAD

**Issue by azurecrash** [mipstian/catch#69]
And the other issue I encountered last night.

I have a number of shows I'm subscribed to on ShowRSS and I've just switched from TVShows2 to Catch. Let's use Falling Skies and Mr. Robot as examples.

TVShows2 has downloaded all episodes of Falling Skies, but none of Mr. Robot as that is a new subscription. Upon switching to Catch, Catch initiates downloads of Falling Skies (to the wrong directory -- see other issue) and begins downloading Mr. Robot as well. Catch creates directories for each as expected. If I then stop these downloads in order to re-set the download directory, and use the Recently Downloaded window to re-initiate the downloads to this new download directory, Catch (a) doesn't place Falling Skies into the existing folder in that directory; and (b) doesn't create a new folder for Mr. Robot.

Perhaps directory creation / checking is only occurring on the initial addition of a new show to the feed?

Hope this helps!

**Comment by mipstian** [comment]
So couple things:
1) The feed itself knows nothing about what you've actually downloaded, that's handled by clients (like Catch). This is why both shows were downloaded when you first moved to Catch - it had no idea what TVShows2 downloaded.
2) Catch only downloads .torrent files inside the download directory (with subdirectories for each show if requested). To get the actual torrent contents in there too, your torrent client must be set to download to the same folder as the .torrent file.

IIRC we don't save show names to the history. This means re-downloaded items won't be organized by show name. That feature is meant for the initial transition to Catch though, so if the only problem is that organization fails when re-downloading, I don't think that's a big deal - you're only gonna have that problem once.

To answer your question, directory creation happens every time any file is downloaded (of course they're only created if they're not there already).

Anyway, I think most of the issue has to do with 2) above. Let me know if this helped.

**Comment by azurecrash** [comment]
Understood regarding #1, and that was not unexpected. With regards to #2, Transmission is set to download files where the torrent files are saved and things worked as expected initially. It was only the re-download that was behaving unexpectedly (to me). Perhaps the more empirical test will occur when a new show pops into the feed. That should tell me (us) more.

Thanks for your prompt reply!

**Comment by mipstian** [comment]
Yeah it should. So I'm gonna close for now, since I don't believe the re-download thing to be a big issue, but if you run into issues with normal downloading by all means let me know!
