### ISSUE TITLE
Catch is preventing sleep

### ISSUE THREAD

**Issue by gnfpt** [mipstian/catch#73]
![catch](https://cloud.githubusercontent.com/assets/9711909/10262155/aa1b9582-69b3-11e5-9578-12591554a065.png)

Catching is preventing sleep. Is it possible to fix this?

**Comment by mipstian** [comment]
Duplicate of #24

**Comment by gnfpt** [comment]
yup, saw that a few moments ago. Sorry

**Comment by mipstian** [comment]
No problem, triaging issues is part of the job :)
