### ISSUE TITLE
Allow user defined save folder for torrent contents

### ISSUE THREAD

**Issue by clarkholdham** [mipstian/catch#74]
Catch is configured to save torrents in a specific directory. This functionality works as expected but it would be convenient to also be able to specify a directory to save the torrent contents. This can be configured from within the torrent client but only offers one location for all torrents. Many people keep there torrent organized into different folders.

**Comment by mipstian** [comment]
Sorry, can't. Where the contents end up is up to the torrent client, not Catch.

What you can do is tell Catch to organize the .torrent files, and then setup your client to always download contents to the same folder where it found the .torrent.
