### ISSUE TITLE
Invalid Torrent File

### ISSUE THREAD

**Issue by dinkyrdj** [mipstian/catch#75]
Hello,
First, my compliments on a great piece of software! I've recently started using catch+ShowRSS. Occasionally I get an error from Transmission saying that a torrent file is invalid. The torrent file has a nonsensical name so I don't know what show it corresponds to. Is there something I can do on my end to address this issue? Thanks,
Ryan

**Comment by mipstian** [comment]
@adrinavarro any input here? Never seen this before.

**Comment by adrinavarro** [comment]
@mipstian Hmmm. The name comes from the info_hash, that's why the file name is so strange. Corruption might happen on the download, caching or could happen because the file is gzipped for some strange reason. I'm afraid I can't be of much help without a more specific example (at least a file name affected)

**Comment by dinkyrdj** [comment]
The latest file this happened on was:

07C0615C143D54AA584AFB9C1519B85406EB2367.torrent.html.torrent

I get an error from Transmission saying it is an invalid torrent and the torrent file ends up in the folder for the show it is associated with (I've select "Organize in folders by show name").

**Comment by mipstian** [comment]
The .html makes me think it's not a torrent at all, probably an error page of sorts. @adrinavarro can probably look up the hash and find out what it was?

**Comment by dinkyrdj** [comment]
If it's any help, this particular torrent was for Heroes Reborn.

**Comment by adrinavarro** [comment]
If you take the info_hash and replace it into a reflektor.karmorra.info URL, then it works properly and is not corrupted. Are you using reflektor or a different torrent source?

It may very well be that an error was thrown on the request concerning your query but it is now working… It happens sometimes. Maybe Catch should look for the linked file headers before saving & counting as good?

**Comment by dinkyrdj** [comment]
@adrinavarro I'm using default settings from ShowRSS, so I'm not exactly sure what torrent source it is.

It almost seems to me that Catch is "catching" the file too soon. If I got to ShowRSS even just a minute or two after the invalid torrent appears, the link on ShowRSS works fine.

**Comment by mipstian** [comment]
Are you maybe using one of those dumb dns services that send you to a dumb error page on error? Can you rename that file to "test.html" and open it in Safari, see what it looks like?

**Comment by dinkyrdj** [comment]
No, I'm not using any dan service. I've attached a screenshot of what happened when I opened "test.html".
![screen shot 2015-10-17 at 8 27 45 am](https://cloud.githubusercontent.com/assets/15134740/10559239/3bad8e42-74a9-11e5-912d-5c662ea2a9cd.png)

**Comment by adrinavarro** [comment]
Yup. It seems that it's just that catch isn't looking at the headers. A 404 response can happen sometimes and then some time after a 200 happens.

**Comment by mipstian** [comment]
So you're saying I should expect URLs in users' feeds to 404 initially sometimes?

**Comment by adrinavarro** [comment]
With reflektor, yes. Simply because a torrent file cannot be found initially.
Happens sometimes when the main source is rarbg, which do not upload newly
created torrents to any cache.
Overall, magnets are way better because of things like this...


On Sat, Oct 17, 2015 at 7:40 PM, Giorgio Calderolla <notifications@github.com>
wrote:
So you're saying I should expect URLs in users' feeds to 404 initially
sometimes?

—
Reply to this email directly or view it on GitHub
[https://github.com/mipstian/catch/issues/75#issuecomment-148937340] .[https://github.com/notifications/beacon/AADKauhX_LVaufgFage-4MaKBAfKz1oHks5o8n-OgaJpZM4GPKOj.gif]

**Comment by mipstian** [comment]
Oh, that's news to me :) Ok I see two scenarios:

1) I would assume the NSURLRequest that downloads the file would fail if it gets a 404 status code, but I might be wrong. That's an easy fix, we can just add two lines two check the statusCode from the NSURLResponse.

2) If the status code is 200 and the server's just serving an error page, we might check the suggested file name and see if it has a non-".torrent" extension. Or at least fail if it gets a ".html" extension.

@adrinavarro do you have a URL that would error so I can check what the status code is, or can you check that? Knowing that for sure would help a lot - I hope it's 1 :)

I think it's ok to set the last check status as "failed" in this case, even it this is expected. But if it's easy, I can make it not fail, and not mark the file as downloaded - so to the user it looks like the episode isn't out yet.

@dinkyrdj as @adrinavarro said, a good workaround for this is to use magnet links (plus, they have other advantages).

**Comment by adrinavarro** [comment]
@mipstian error URL — sure! Just do a 40-byte-long caps string. For
example:
http://reflektor.karmorra.info/torrent/640FE84C613C17F663551D218689A64E8AEBEABA.torrent

Cached miss means it won't try again until 1h later (to avoid hitting and
missing all mirrors constantly). But maybe 1h later it will be a hit (and
then cached forever) because a torrent for that hash was uploaded
somewhere. It can also happen that reflektor gives a miss and a hit and
then a miss (there are several caches running) until the situation
stabilizes (max 1h).

Overall — torrent files suck. Most torrent caches have disappeared, only
torcache is left running now. It's a quite dire situation.

**Comment by rarbg** [comment]
@adrinavarro 
Actually we do upload any torrent on our site to torcache :)

**Comment by dinkyrdj** [comment]
@mipstian I happy to try magnets as opposed to torrents. I did find when I updated my ShowRSS feed to allow magnets, Transmission no longer would auto download the files. I had to tell it where to put them. I found I can fix this by changing a setting in Transmission but then Catch doesn't put the shows into directories by show name. 

Question is - does Catch support using magnets AND organizing shows by show name?

**Comment by mipstian** [comment]
No, I can't tell the torrent client where to put the contents of the magnet.

**Comment by adrinavarro** [comment]
@rarbg I shall shut up then! Once torcache goes — are you eyeing another cache?

**Comment by adrinavarro** [comment]
@dinkyrdj / @mipstian: classifying shows by folders shouldn't be a task
left to pre-loading or torrent clients, but instead, performed by a
post-processing software (ie. library management)

**Comment by mipstian** [comment]
Agreed.

**Comment by rarbg** [comment]
@adrinavarro 
I really didnt understand your question
Are you asking if torcache goes offline what will happen ? Because torcache is operated by KAT

**Comment by adrinavarro** [comment]
Torrage went out, zoink went with eztv as well, etc etc. Most of the
working torrent caches are now gone and only torcache is left standing. And
now, KAT is doing massive deletions for DMCA at an alarming pace. So, yeah…
just wondering if there's a plan B other than magnets

**Comment by rarbg** [comment]
:) There is always a plan B,C,D , so dont worry about that
torcache.net
thetorrent.org
btdig.com
itorrents.org
Here is a small list of the working torrent caches that you can use

**Comment by adrinavarro** [comment]
Brilliant! Thanks :)

**Comment by mipstian** [comment]
That should do it, easy fix. Can someone else build from master and run this for a while?

**Comment by dinkyrdj** [comment]
Thanks for the help! 

May I make one suggestion? If magnets are supported but don't work with organizing by show, make this clear in the documentation? The configuration page shows that magnets work but a note saying that they won't work with organizing show by folder would be nice. As I said, just a suggestion. 

@ mipstian You've put together a really great piece of software and have been very responsive. Do you accept donations? Thank you!

**Comment by mipstian** [comment]
Thanks for the tip, I've updated/modernized the guide here: https://github.com/mipstian/catch/wiki/Configuration

No donations but I do develop commercial software for iOS and Mac, so if you see something you like at giorgiocalderolla.com and/or feel an uncontrollable urge to tell your friends about it, feel free :)
