### ISSUE TITLE
Add support for generic namespaces

### ISSUE THREAD

**Issue by showrss** [mipstian/catch#77]
As an improvement for Catch, I would like to suggest support for generic feeds and namespace naming, instead of it being strictly specific to showRSS.

This means:
- Instead of checking the URL format, check the content of the given URL to see if it is a valid format
- Accepting generic namespace tags, in addition to the ones that are currently support.

The proposed namespace tags are:

- tv:show_id (equivalent to showrss:showid)
- tv:show_name (equivalent to showrss:showname)
- tv:episode_id (equivalent to showrss:episode)
- tv:raw_title (equivalent to showrss:rawtitle)
- tv:info_hash (equivalent to showrss:info_hash)

Thanks! :)

**Comment by mipstian** [comment]
Done in 780d57f84fa4f06831848704c3fbca35a54438f5 and c1548579a630f5ebb4cf168ea33a8afff65e2131
