### ISSUE TITLE
Catch hangs when receiving .torrent files, but works with magnets

### ISSUE THREAD

**Issue by edcorcoran** [mipstian/catch#78]
When I use my ShowRSS feed with the option to disable magnets (which plays nicer with automatically launching a file in Transmission and putting it in the appropriate folder), Catch hangs when refreshing and never completes. 

However, when I use magnets it works fine. The only problem is I have to manually select the file location in Transmission. Not a huge problem, but an annoyance nonetheless as it prevents full automation.

The URL that doesn't work is:
http://showrss.info/rss.php?user_id=XXXXXXX&hd=null&proper=null&magnets=false&namespaces=true

The URL that works is:
http://showrss.info/rss.php?user_id=XXXXXXX&hd=null&proper=null&namespaces=true

Please let me know what troubleshooting I can do to help diagnose this problem.

**Comment by mipstian** [comment]
(Just FYI there is a way to setup Transmission to never prompt you when opening magnets. I have it setup that way and it's fully automated.)

I'm assuming Catch is trying to download a .torrent file and the server isn't responding, but to confirm:
1) Please launch Console.app
2) Select "all messages" on the left, type "catch" in the filter box, click "clear display" in the toolbar
3) Reproduce the issue in Catch
4) Select everything that appeared in Console, copy, and paste here (possibly in a code box)

Thanks!

**Comment by edcorcoran** [comment]
Here's the console output:

11/1/15 11:03:11.130 PM Catch[35574]: Adding app to login items
11/1/15 11:03:11.132 PM Catch[35574]: Forcing feed check
11/1/15 11:03:11.132 PM Catch[35574]: Scheduler status updated (polling = 1, checking = 1)
11/1/15 11:03:11.133 PM com.giorgiocalderolla.Catch.CatchFeedHelper[35576]: Checking feed
11/1/15 11:03:11.134 PM com.giorgiocalderolla.Catch.CatchFeedHelper[35576]: Downloading feed http://showrss.info/rss.php?user_id=36548&hd=null&proper=null&magnets=false&namespaces=true
11/1/15 11:03:11.455 PM com.giorgiocalderolla.Catch.CatchFeedHelper[35576]: Feed downloaded
11/1/15 11:03:11.455 PM com.giorgiocalderolla.Catch.CatchFeedHelper[35576]: Parsing feed
11/1/15 11:03:11.456 PM com.giorgiocalderolla.Catch.CatchFeedHelper[35576]: Parsed 6 files
11/1/15 11:03:11.456 PM com.giorgiocalderolla.Catch.CatchFeedHelper[35576]: Downloading files (if needed)
11/1/15 11:03:11.456 PM com.giorgiocalderolla.Catch.CatchFeedHelper[35576]: Downloading file to folder American Horror Story
11/1/15 11:03:29.106 PM Catch[35574]: Forcing feed check
11/1/15 11:04:11.457 PM com.giorgiocalderolla.Catch.CatchFeedHelper[35576]: Could not download http://torrage.com/torrent/26E49E9C0C805097A1657CFA30BA136B8B5F07BA.torrent: Error Domain=com.giorgiocalderolla.Catch.CatchFeedHelper Code=-1 "Could not download file" UserInfo={NSLocalizedDescription=Could not download file, NSUnderlyingError=0x7ff331703540 {Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSUnderlyingError=0x7ff331413100 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=http://torrage.com/torrent/26E49E9C0C805097A1657CFA30BA136B8B5F07BA.torrent, NSErrorFailingURLKey=http://torrage.com/torrent/26E49E9C0C805097A1657CFA30BA136B8B5F07BA.torrent, _kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4, NSLocalizedDescription=The request timed out.}}, NSErrorFailingURLStringKey=http://torrage.com/torrent/26E49E9C0C805097A1657CFA30BA136B8B5F07BA.torrent, NSErrorFailingURLKey=http://torrage.com/torrent/26E49E9C0C805097A1657CFA30BA136B8B5F07BA.torrent, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=The request timed out.}}}
11/1/15 11:04:11.457 PM com.giorgiocalderolla.Catch.CatchFeedHelper[35576]: Downloading file to folder Fargo
11/1/15 11:05:11.458 PM com.giorgiocalderolla.Catch.CatchFeedHelper[35576]: Could not download http://torrage.com/torrent/E09FBF4AAC8D2EB3E129FB6CE2B49BBD168AB7DE.torrent: Error Domain=com.giorgiocalderolla.Catch.CatchFeedHelper Code=-1 "Could not download file" UserInfo={NSLocalizedDescription=Could not download file, NSUnderlyingError=0x7ff331417d50 {Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSUnderlyingError=0x7ff331405dd0 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=http://torrage.com/torrent/E09FBF4AAC8D2EB3E129FB6CE2B49BBD168AB7DE.torrent, NSErrorFailingURLKey=http://torrage.com/torrent/E09FBF4AAC8D2EB3E129FB6CE2B49BBD168AB7DE.torrent, _kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4, NSLocalizedDescription=The request timed out.}}, NSErrorFailingURLStringKey=http://torrage.com/torrent/E09FBF4AAC8D2EB3E129FB6CE2B49BBD168AB7DE.torrent, NSErrorFailingURLKey=http://torrage.com/torrent/E09FBF4AAC8D2EB3E129FB6CE2B49BBD168AB7DE.torrent, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=The request timed out.}}}

**Comment by mipstian** [comment]
There you go, all downloads are timing out. @adrinavarro is torrage broken?

**Comment by adrinavarro** [comment]
Torrage has been dead for a while already. When in doubt, use reflektor…

**Comment by edcorcoran** [comment]
Ah ha! thanks!

I didn't know I could select different link mirrors in ShowRSS.

**Comment by mipstian** [comment]
@edcorcoran does that mean the issue is resolved? :)

**Comment by edcorcoran** [comment]
Yep. Closing now.
