### ISSUE TITLE
Should Catch check for 5XX errors on download?

### ISSUE THREAD

**Issue by joshuag** [mipstian/catch#79]
Occasionally (especially lately), Catch will receive a 502 from wherever it is receiving torrent files. I would propose that Catch check for server error codes and refetch the file at a later point, perhaps with an exponential decay.

However, the content of the .torrent file is HTML, so it may be that nginx delivers a 200 along with an HTML page describing the 502 error from the upstream application.

```<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.8.0</center>
</body>
</html>
```

**Comment by mipstian** [comment]
This should be covered by 7af57b9286e6e77127ecdd1e6bf791a2127e6058
Please reopen if I misunderstood :)

**Comment by joshuag** [comment]
Yep! I should have reviewed the commits before submitting the ticket. Thanks for taking a look!

**Comment by mipstian** [comment]
Nah, reviewing commit logs is too much to ask for bug reporters I think. Triaging issues is just part of the job :)
