### ISSUE TITLE
Add a wishlist to remember future show

### ISSUE THREAD

**Issue by Kitefr** [mipstian/catch#81]
The possibility to add a list to store future shows name.

If ShowRss release a show with that name - or a similar one -, we can get notified !
Because we cannot add future shows in ShowRss until the staff add them themselves.

Thanks for your time and work.

**Comment by mipstian** [comment]
This sounds more like a ShowRSS request than a Catch one. Being that ShowRSS is where shows are selected, I think it makes sense that this feature would be implemented there as well. @adrinavarro ?

**Comment by showrss** [comment]
There's no plan to implement such a feature in the website — sorry.

**Comment by mipstian** [comment]
Guess you'll just have to wait for a few months until all shows are added :)
