### ISSUE TITLE
Need help for saving folder

### ISSUE THREAD

**Issue by Kitefr** [mipstian/catch#82]
Hello,

I've got catch working pretty great and i love it but i encounter a problem.

First, my Transmission configuration is, by default, to use the `Downloads` folder.
In Catch, i set a `tvseries` folder inside the `Downloads` default folder.

But when transmission finish a download, those are send to the `Downloads` folder instead of the `tvseries` one. Maybe I did something wrong ?

**Comment by mipstian** [comment]
Are you using magnet links? Magnet links are great, but the downside is that Catch has no control over where they're saved. Basically all the settings in the "torrent files" box only apply to torrent *files*, not magnet links.

You can disable magnet links in your feed if that's acceptable to you.

**Comment by Kitefr** [comment]
Yes i was using magnet files. Thanks for the heads up.
I found a way to overcome this "problem" !
I am using Transmission Group rules to save the files in the right folder.
If the file have some specific keyword used for tv shows, it will use the specific group.

Thanks, I am closing.
