### ISSUE TITLE
Can't validate settings

### ISSUE THREAD

**Issue by nhoizey** [mipstian/catch#83]
I don't know why catch doesn't want to save my settings.

There's an exclamation mark next to the feed URL, but no explanation.

Here is my feed URL : http://showrss.info/user/571.rss?magnets=true&namespaces=true&name=clean&quality=hd&re=no

**Comment by mipstian** [comment]
That's a new ShowRSS feed. It works for me. Are you running Catch 1.9.3? That's the only version that supports these new feeds.

**Comment by nhoizey** [comment]
I was running 1.9.2, I don't know why auto update didn't work.

Thanks.
