### ISSUE TITLE
new.showrss.info link not working

### ISSUE THREAD

**Issue by consumedsoul** [mipstian/catch#86]
with the upgrade of new.showrss.info - the generated links aren't working/compatible with catch - is this being worked on?

**Comment by Niphery** [comment]
Update to 1.9.3 => https://github.com/mipstian/catch/releases
It fixed it for me.

**Comment by consumedsoul** [comment]
So awesome - thanks!

**Comment by mipstian** [comment]
Automated triage, I like it :)
