### ISSUE TITLE
beside the feed url setting I have an exclamation point

### ISSUE THREAD

**Issue by antkn33** [mipstian/catch#87]
I don't know why it is there and it won't let me save the setting. I am using v 1.91
\This is the feed url I am trying to use http://showrss.info/user/3622.rss?magnets=false&namespaces=true&name=null&quality=null&re=null

**Comment by mipstian** [comment]
Use 1.9.3 :)
The reason why that URL isn't accepted is because it's a "new showrss" url. Which we added support for in 1.9.3.
