### ISSUE TITLE
Catch should not cause magnet and torrent links to automatically open

### ISSUE THREAD

**Issue by boneskull** [mipstian/catch#92]
This seems like a fairly (?) recent change, but it's broken for me.  At the very least, there should be a option to disable this behavior.  Use case:

All of my torrents are opened by a [Deluge](http://deluge-torrent.org/) daemon running on another machine.  The other machine shares a directory over NFS; `.torrent` files I download are placed into this directory, and `deluged` adds them automatically.

FWIW, Transmission.app *also* has this behavior (as it can watch a directory and automatically add `.torrent` files).  Transmission.app can be configured to start at login, like Catch.app.

Not sure if you are following semantic versioning, but it appears this was a breaking change that would have necessitated a major release.

I'm not a big Obj-C guy, but I could *probably* flail about a bit and send a PR that adds an option to the configuration window.

**Comment by boneskull** [comment]
Actually... if I switch to disabling magnet links on ShowRSS, then it works as expected.

**Comment by boneskull** [comment]
I think this is probably a non-issue, but perhaps it should be mentioned that regardless of whether or not the "Open Automatically" checkbox is ticked, magnet links will always cause the default URL handler to open.

**Comment by mipstian** [comment]
Thanks for reporting.

There's a tentative plan to build UI to replace pasting ShowRSS URLs with buttons and switches in 2.0. With that in place, non-magnet options will only appear when unchecking "use magnet links".

Without UI changes, I think the current behavior is the best compromise - the alternative would be to silently discard magnet links which essentially breaks the app.
