### ISSUE TITLE
Showrss updated

### ISSUE THREAD

**Issue by mikaelkristiansson** [mipstian/catch#95]
ShowRss have updated their site so could you please adapt the changes so catch work with the new one?

**Comment by mipstian** [comment]
Done in 1.9.3! If you're referring to the "Launch ShowRSS" menu item, please read #84 or https://docs.google.com/document/d/1DCWQ54Vd7GZO00yk9ljtbE-2D1TNeDWjm7oOXUPLvCY/edit?pref=2&pli=1
