### ISSUE TITLE
Unsure if opting out of 'open automatically' is working correctly. (getting angry letters from ISP:)

### ISSUE THREAD

**Issue by Outside-Kitty** [mipstian/catch#96]
Hello Mr. Calderolla,

First off thank you for this application, works wonderfully and is super simple/light. I also respect the lack of donation requests on your website. I would however like to thank you with a small token of monetary gratitude, if you please. 

That said, What I'm trying to trouble shoot is my not receiving growl push notifications for torrents being auto added to Transmission.

With Otomatic 2 I was getting 'torrent file automatically added' notifications sent to Growl via Transmission. With Catch I'm not getting those notifications anymore. I've unchecked the 'open automatically' option in Catch, but I'm not sure that's working. 

Best I as understand, Transmission app sends a notice to Growl when the app itself opens a torrent file from the monitored folder. I tested this by saving a torrent file to the watch folder outside of Catch, and the notification went through as planned. 

So I think there might be something happening from Catch, perhaps the option isn't configured complete for El Capitan? 

20089 Mac Mini  
OS X 10.11.2
Catch 1.9.3
Transmission 2.84 (14306)
Growl 2.1.3

**Comment by mipstian** [comment]
Hi! No donations thanks, if you'd like you can check out my apps at giorgiocalderolla.com and see if there's something you like :)

First off, Catch doesn't use Growl (anymore), it uses OS X's notification center. Notifications are sent when a new torrent is found in your feed.

I can't help you with Transmission's notifications, sorry :)

The "open automatically" option only applies to torrent *files*. Meaning that if you use magnet links in your feed (which is the default now), they will open automatically regardless. You can check if you're using magnets by looking at your feed url, it will contain "magnets=true" if you do, "magnets=false" if you don't.

I'm closing, but please reopen or reply if this doesn't solve your issue.
