### ISSUE TITLE
Catch doesn't work with the new ShowRSS

### ISSUE THREAD

**Issue by ccarnino** [mipstian/catch#99]
After migrating ShowRSS to the new version of the website, the feed URL changes. The new one has different URL components, so Catch is not recognising it as valid.

The problem is that the old URL stop working (probably disabled by ShowRSS).

How can I help?

**Comment by studiosciences** [comment]
Download version 1.9.3. See issue #84.

**Comment by ccarnino** [comment]
Thanks for the info
